art/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('shop.urls', 'shop'), namespace='shop')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("",views.index,name="index"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path("view/<slug>/",views.ArtworkDetailView.as_view(),name="view"),
    path("cart/",views.cart,name="cart"),
    path("checkout/",views.checkout,name="checkout"),
    path("customize/",views.customize,name="customize"),
    path("update_item/",views.updateItem,name="update_item"),
    path("process_order/",views.processOrder,name="process_order"),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

# Create your models here.
class Customize(models.Model):
    name=models.CharField(max_length=100,null=True)
    phone=models.CharField(max_length=12)
    email=models.CharField(max_length=100)
    dimensions=models.CharField(max_length=10)
    img=models.ImageField(upload_to='shop/artworks')
    date=models.DateField()


class Artwork(models.Model):
    art_name=models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    artist_name=models.CharField(max_length=100)
    pub_date=models.DateField()
    price=models.IntegerField()
    dimension=models.CharField(max_length=100,default="")
    image=models.ImageField(upload_to='shop/artworks')
    slug=models.SlugField(default="")

    def __str__(self):
        return self.art_name

    def get_absolute_url(self):
        return reverse("shop:view",kwargs={
            'slug':self.slug
        })

    @property
    def imageURL(self):
        try:
           url = self.image.url
        except:
           url = ''
        return url

class Customer(models.Model):
    user=models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)
    name=models.CharField(max_length=100,null=True)
    email=models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    #@property
    #def shipping(self):
    #    shipping=True
    #    return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Artwork, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total=self.product.price*self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import DetailView
from django.http import JsonResponse
from django.contrib import messages
import json
from datetime import datetime
from .forms import NewUserForm
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.forms import AuthenticationForm
from  .models import *
from . utils import cookieCart,cookieData,guestOrder

# Create your views here.
def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("shop:index")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm
	return render (request=request, template_name="shop/register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("shop:index")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="shop/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("shop:index")

def customize(request):
    if request.method=="POST":
        name=request.POST.get('name')
        phone=request.POST.get('phone')
        email=request.POST.get('email')
        dimensions=request.POST.get('dimensions')
        img=request.POST.get('img')
        customize=Customize(name=name,phone=phone,email=email,dimensions=dimensions,img=img,date=datetime.today())
        customize.save()
    return render(request,'shop/customize.html')

def index(request):
    products= Artwork.objects.all()
    context={'products':products}
    return render(request,'shop/index.html',context)


class ArtworkDetailView(DetailView):
    model=Artwork
    template_name="shop/view.html"

def about(request):
    context={}
    return render(request,'shop/about.html',context)

def cart(request):
    data=cookieData(request)
    order=data['order']
    items=data['items']

    context={'items':items,'order':order}
    return render(request,'shop/cart.html',context)


def checkout(request):
    data=cookieData(request)
    order=data['order']
    items=data['items']

    context={'items':items,'order':order}
    return render(request,'shop/checkout.html',context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user.customer
    product = Artwork.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('hi',safe=False)

def processOrder(request):
    transaction_id=datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    ShippingAddress.objects.create(
        customer=customer,
        order=order,
        address=data['shipping']['address'],
        city=data['shipping']['city'],
        state=data['shipping']['state'],
        zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('payment complete',safe=False)

shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mains1.css' %}">
    <script type="text/javascript">
        var user='{{request.user}}'
        function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
         }
        var csrftoken = getToken('csrftoken')

        function getCookie(name) {
        // Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");

        // Loop through the array elements
        for(var i = 0; i < cookieArr.length; i++) {
            var cookiePair = cookieArr[i].split("=");

            /* Removing whitespace at the beginning of the cookie name
            and compare it with the given string */
            if(name == cookiePair[0].trim()) {
                // Decode the cookie value and return
                return decodeURIComponent(cookiePair[1]);
            }
        }

        // Return null if not found
        return null;
    }
    var cart = JSON.parse(getCookie('cart'))

    if (cart == undefined){
      cart = {}
      console.log('Cart Created!', cart)
      document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
    }
    console.log('Cart:', cart)
    </script>
    <title>{% block title %} {% endblock %}</title>

    {% block css %} {% endblock css %}
  </head>
  <body id="home">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark scrolling navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'shop:index' %}"><b>s2s</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:customize' %}">Customize</a>
        </li>
      </ul>

      <div class="form-inline my-2 my-lg-0">
        {% if user.is_authenticated %}
        <a class="btn btn-danger" href="/logout">Logout</a>
        {% else %}
        <a class="btn btn-success" href="/login">Login</a>
        <a class="btn btn-primary" href="/register">Signup</a>
        {% endif %}
        <a href="{% url 'shop:cart' %}">
          <img id="cart-icon" src="{% static 'images/cart.png' %}">
        </a>
      </div>
    </div>
  </div>
</nav>
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}
<div class="container">
  {% block content %}
  {% endblock content %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script text="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

shop/templates/shop/cart.html
{% extends 'shop/base.html' %}
{% block title %}Cart | S2S{% endblock title %}
{% load static %}
{% block content %}

<div class="row">
<div class="col-lg-12">
  <div class="box-element">

    <table class="table">
      <tr>
        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
        <th><h5>Total:<strong> {{order.get_cart_total}}</strong></h5></th>
      </tr>
    </table>

  </div>

  <br>
  <div class="box-element">
    <div class="cart-row">
      <div style="flex:2"></div>
      <div style="flex:2"><strong>Item</strong></div>
      <div style="flex:1"><strong>Price</strong></div>
      <div style="flex:1"><strong>Quantity</strong></div>
      <div style="flex:1"><strong>Total</strong></div>
    </div>
  {% for item in items %}
    <div class="cart-row">
      <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
      <div style="flex:2"><h5>{{item.product.art_name}}</h5></div>
      <div style="flex:1"><p>{{item.product.price}}</p></div>
      <div style="flex:1">
        <p class="quantity">{{item.quantity}}</p>
        <div class="quantity">
          <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/up.png' %}">

          <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/down.png' %}">
        </div>
      </div>
      <div style="flex:1"><p>{{item.get_total}}</p></div>
    </div>
 {% endfor %}
   <a  class="btn btn-outline-dark" href="{% url 'shop:index' %}">&#x2190; Continue Shopping</a>
   <a id="check" style="float:right; margin:5px;" class="btn btn-success" href="{% url 'shop:checkout' %}">Checkout</a>
  </div>
</div>
</div>

<script type="text/javascript">
  if({{order.get_cart_items}}=='0'){
    document.getElementById('check').classList.add("hidden");
  }
</script>
{% endblock content %}

shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Checkout | S2S{% endblock title %}
{% block content %}
  <div class="container">
    <div class="col-lg-12">
      <div class="box-element">
        <a  class="btn btn-outline-dark" href="{% url 'shop:cart' %}">&#x2190; Back to Cart</a>
        <hr>
        <h3>Order Summary</h3>
        <hr>
        {% for item in items %}
        <div class="cart-row">
          <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
          <div style="flex:2"><p>{{item.product.art_name}}</p></div>
          <div style="flex:1"><p>{{item.product.price}}</p></div>
          <div style="flex:1"><p>{{item.quantity}}</p></div>
        </div>
        {% endfor %}
        <h5>Items:   {{order.get_cart_items}}</h5>
        <h5>Total:   ${{order.get_cart_total}}</h5>
      </div>
    </div>
		<div class="col-lg-12">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
					</div>

					<br>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
        <div id="paypal-button-container"></div>
			</div>

		</div>


  </div>
<script src="https://www.paypal.com/sdk/js?client-id=AcPybcudYf6Eg7VZCTqknoChA6oH1IAQURPaakInWZdwfHPk_5JOMuOI-llR3CuM5mcKDr2AeQLzjf9M&currency=INR"></script>
<script>
       // Render the PayPal button into #paypal-button-container
       var total='{{order.get_cart_total}}'
       paypal.Buttons({
         style: {
             color:  'blue',
             shape:  'pill',
             label:  'pay',
             height: 40
         },

           // Set up the transaction
           createOrder: function(data, actions) {
               return actions.order.create({
                   purchase_units: [{
                       amount: {
                           value: total
                       }
                   }]
               });
           },

           // Finalize the transaction
           onApprove: function(data, actions) {
               return actions.order.capture().then(function(details) {
                   submitFormData()
               });
           }


       }).render('#paypal-button-container');
</script>
<script type="text/javascript">
  var shipping

  if (user != 'AnonymousUser'){
    document.getElementById('user-info').innerHTML = '';
  }

  var form = document.getElementById('form')
	form.addEventListener('submit', function(e){
      e.preventDefault()
      console.log('Form Submitted...')
	    document.getElementById('form-button').classList.add("hidden");
	    document.getElementById('payment-info').classList.remove("hidden");
	 })

   /*document.getElementById('make-payment').addEventListener('click', function(e){
       submitFormData()
     })*/
	    function submitFormData(){
	    	console.log('Payment button clicked')

	    	var userFormData = {
				'name':null,
				'email':null,
				'total':{{order.get_cart_total}},
			}

			var shippingInfo = {
				'address':form.address.value,
				'city':form.city.value,
				'state':form.state.value,
				'zipcode':form.zipcode.value,
			}
	    	if (user == 'AnonymousUser'){
	    		userFormData.name = form.name.value
	    		userFormData.email = form.email.value
	    	}
        var url = "/process_order/"
	    	fetch(url, {
	    		method:'POST',
	    		headers:{
	    			'Content-Type':'applicaiton/json',
	    			'X-CSRFToken':csrftoken,
	    		},
	    		body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),

	    	})
	    	.then((response) => response.json())
	    	.then((data) => {
				console.log('Success:', data);
				alert('Transaction completed');
        cart={}
        document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
				window.location.href = "{% url 'shop:index' %}"

				})
      }



</script>

{% endblock content %}

shop/templates/shop/customize.html
{% extends 'shop/base.html' %}
{% block title %} Customize | S2S {% endblock %}
{% block content %}
<br>
<form method="post" action="/customize/" class="box-element">
  {% csrf_token %}
  <div class="form-floating mb-3">
    <input type="text" class="form-control" id="name" name="name">
    <label for="name">Name</label>
  </div>
  <div class="form-floating mb-3">
    <input type="phone" class="form-control" id="phone" name="phone">
    <label for="phone">Phone Number</label>
  </div>
  <div class="form-floating mb-3">
    <input type="email" class="form-control" id="email" name="email">
    <label for="email">Email address</label>
  </div>
  <div class="form-floating">
    <input type="text" class="form-control" id="dimensions" name="dimensions">
    <label for="dimensions">Dimensions required in cm</label>
  </div>
  <br>
  <br>
  <div class="mb-3">
    <label for="formFile" class="form-label" id="img">Upload Image</label>
    <input class="form-control" type="file" id="img" name="img">
  </div>
  <button class="btn btn-primary" type="success">Submit</button>
  <h3 style="text-align:center">You will be contacted through email for further details.</h3>
</form>
{% endblock content %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Home | S2S{% endblock title %}
{% block css %}
<style>

  .test{
    width: 300px;
    height: 300px;
  }
  .circleborder {
    padding: 5px;
    border: 4px solid #d5a770;
    display: inline-block;
  }
</style>
 {% endblock css %}

  {% block content %}


<br>
<br>



<div>
  <div class="row">
    {% for product in products %}
    <div class="col-lg-4">
      <a href="{{ product.get_absolute_url }}"><img class="rounded-circle test circleborder" src="{{product.imageURL}}"></a>
    </div>
    {% endfor %}
  </div>
</div>



{% endblock content %}

shop/templates/shop/login.html
{% extends "shop/base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Login-->

<div class="container py-5">
  <div class="box-element">
  <h1>Login s2s</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <br>
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
  </div>
</div>

{% endblock content %}

shop/templates/shop/register.html
{% extends "shop/base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
  <div class="box-element">
	<h1>SignUp s2s</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">SignUp</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
  </div>
</div>

{% endblock %}

shop/templates/shop/view.html
{% extends 'shop/base.html' %}
{% block title %}View | S2S{% endblock title %}
{% load static %}
{% block content %}

<main class="mt-5 pt-4 box-element">
    <div class="container dark-grey-text mt-5">
      <div class="row wow fadeIn">
        <div class="col-md-6 mb-4">
          <img src="{{object.imageURL}}" class="img-fluid" alt="">
        </div>
        <div class="col-md-6 mb-4">
          <div class="p-4">
            <p><b>{{object.art_name}}</b></p>
            <hr>
            <p class="lead">
              <span>${{ object.price }}</span>
            </p>
            <p>Artist : "{{object.artist_name}}"</p>
            <p>Dimensions : "{{object.dimension}}"</p>
            <form class="d-flex justify-content-left">
               <button data-product={{object.id}} data-action="add" class="btn btn-primary btn-md my-0 p update-cart show">Add to cart</button>
            </form>
           </div>
        </div>
      </div>
      <hr>
    </div>
  </main>

  {% endblock content %}